repos:
  - repo: local
    hooks:
      - id: trufflehog
        name: TruffleHog
        description: Detect secrets in your data.
        entry: bash -c 'trufflehog git file://. --since-commit HEAD --no-verification --fail --max-depth=1'
        # run no verification and max-depth 1 for only latest commit
        language: system
        stages: ["commit", "push"]